const VIDEOS: any[] = [
  {
    type: "Video",
    id: "41776244",
    attributes: {
      id: "41776244",
      title:
        "مخلوط اسلایم های شفاف و خامه ای/ واتر اسلایم های کیوت/ آموزش ساخت اسلایم ژله ای",
      description:
        "سلام بچه ها چطورید ، بچه ها داخل این ویدیو اسلایم های شفاف و خامه ای را برایتان آورده ام امیدوارم که لذت ببرید لایک ، کامنت و دنبال کردن فراموش نشود و حتما بازنشر هم بکنید \n..............................................................................................\nبه ویدیو های قبلی من هم سر بزنید خیلی دوستون دارم",
      username: "rtaarcade",
      userid: "11077168",
      tags: null,
      process: "no_stat",
      sender_name: "ARTA ARCADE",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41776244-5415-b__890874156.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41776244-5415__5346.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/11077168-m.jpg",
      duration: "559",
      sdate: "03 بهمن 1400",
      sdate_timediff: 42671,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/XBHE7/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: "0",
      like_cnt: "181",
      comment_cnt: 29,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41776244_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "4",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41783886",
    attributes: {
      id: "41783886",
      title: "سرنا امینی طنز باحال",
      description:
        "سلام بچه ها امروز دوتا پست گذاشتم \nامیدوارم حالتون خوب باشه",
      username: "Lookop",
      userid: "10482512",
      tags: null,
      process: "no_stat",
      sender_name: "✓(خنده).....{happy}™_™(بامزه)........{funne}✓",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41783886-5253-b__740299518.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41783886-5253__3531.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/10482512-m.jpg",
      duration: "231",
      sdate: "03 بهمن 1400",
      sdate_timediff: 30302,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/1N24L/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: "0",
      like_cnt: "277",
      comment_cnt: 17,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41783886_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "2",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41786742",
    attributes: {
      id: "41786742",
      title:
        "آنباکسینگ بهترین تخم مرغ شانسی با داداشم / داداشم اصلا شانس نداشت",
      description: "بچه ها لایک و کامنت یادتون نره .",
      username: "dashadib",
      userid: "2025696",
      tags: null,
      process: "no_stat",
      sender_name: "havzhin blog (هاوژین محمدی)",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41786742-7265-b__823240503.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41786742-7265__3155.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/2025696-m.jpg",
      duration: "233",
      sdate: "03 بهمن 1400",
      sdate_timediff: 25592,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/gob2G/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: "0",
      like_cnt: "246",
      comment_cnt: 3,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41786742_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "4",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41783630",
    attributes: {
      id: "41783630",
      title:
        "چالش ها و موقعیت های خنده دار ترفندهای خفن تلفن همراه/تفریحی سرگرمی بانوان GO123",
      description: "",
      username: "monlightmag",
      userid: "5984949",
      tags: null,
      process: "no_stat",
      sender_name: "❤ تفریحی و سرگرمی بانوان ❤",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41783630-3530-b__603157467.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41783630-3530__5911.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/5984949-m.jpg",
      duration: "484",
      sdate: "03 بهمن 1400",
      sdate_timediff: 30742,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/mROLw/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: "0",
      like_cnt: "43",
      comment_cnt: 47,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41783630_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "4",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41782700",
    attributes: {
      id: "41782700",
      title:
        "تفریحی سرگرمی بانوان GO123/چالش ها و موقعیت های خنده دار غذایی و شوخی با دوستان",
      description: "",
      username: "monlightmag",
      userid: "5984949",
      tags: null,
      process: "no_stat",
      sender_name: "❤ تفریحی و سرگرمی بانوان ❤",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41782700-1911-b__946130626.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41782700-1911__5472.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/5984949-m.jpg",
      duration: "266",
      sdate: "03 بهمن 1400",
      sdate_timediff: 32233,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/Fs0Tp/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: "0",
      like_cnt: "56",
      comment_cnt: 39,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41782700_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "4",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41785530",
    attributes: {
      id: "41785530",
      title: "جواب به سوالات شما | چرا برگشتی ایران ؟؟ (حامی کی ام)",
      description:
        "ویدیوی جدید حامی کی ام جواب به سوالات شما | چرا برگشتی ایران ؟؟ لینک ویدیوی اصلی چنل حامی کی ام https://youtu.be/5S0ISNBxuP4 لینک دیسکورد حامی کی ام https://discord.gg/8VhYSYjd9G",
      username: "keivan.8",
      userid: "624862",
      tags: null,
      process: "no_stat",
      sender_name: "★★..::..Onur Alkan..::..★★",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41785530-2798-b__957022459.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41785530-2798__5192.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/624862-m.jpg",
      duration: "560",
      sdate: "03 بهمن 1400",
      sdate_timediff: 27555,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/Rs3cm/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: "0",
      like_cnt: "84",
      comment_cnt: 22,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41785530_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "4",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41783907",
    attributes: {
      id: "41783907",
      title: "حمله به مراسم تدفین در ویدیو جدید فیلم بتمن",
      description:
        "ویدیو جدیدی از فیلم The Batman منتشر شده است که در آن ریدلر برای رساندن پیامش به بتمن به مراسم تدفین حمله می‌کند.",
      username: "zoomg",
      userid: "456905",
      tags: null,
      process: "no_stat",
      sender_name: "زومجی - سرگرمی زیر ذره بین",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41783907-4608-b__646757725.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41783907-4608__7643.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/456905-m.jpg",
      duration: "161",
      sdate: "03 بهمن 1400",
      sdate_timediff: 30273,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/p4JNe/vt/frame",
      official: "yes",
      autoplay: true,
      "360d": false,
      brand_priority: "88888",
      like_cnt: "12",
      comment_cnt: 22,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41783907_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "5",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41772210",
    attributes: {
      id: "41772210",
      title:
        "اتلتیکو مادرید ۳-۲ والنسیا | خلاصه بازی | کامبک فوق‌العاده شاگردان سیمئونه",
      description: "پیروزی اتلتیکو مادرید مقابل والنسیا در هفته ۲۲ لالیگا",
      username: "AparatSport",
      userid: "9990286",
      tags: null,
      process: "no_stat",
      sender_name: "آپارات ورزشی",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41772210-7383-b__530613400.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41772210-7383__1414.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/9990286-m.jpg",
      duration: "287",
      sdate: "03 بهمن 1400",
      sdate_timediff: 52984,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/wRUoZ/vt/frame",
      official: "yes",
      autoplay: true,
      "360d": false,
      brand_priority: "88888",
      like_cnt: "36",
      comment_cnt: 30,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41772210_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "11",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41785624",
    attributes: {
      id: "41785624",
      title:
        "چالش و موقعیت های خنده دار/غذایی و شوخی های دیوانه کننده/ تفریحی سرگرمی بانوان",
      description: "",
      username: "monlightmag",
      userid: "5984949",
      tags: null,
      process: "no_stat",
      sender_name: "❤ تفریحی و سرگرمی بانوان ❤",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41785624-8070-b__128963187.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41785624-8070__5699.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/5984949-m.jpg",
      duration: "374",
      sdate: "03 بهمن 1400",
      sdate_timediff: 27425,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/lghYE/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: "0",
      like_cnt: "45",
      comment_cnt: 38,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41785624_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "4",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "41785262",
    attributes: {
      id: "41785262",
      title: "چجوری گوشی موبایلو به وب کم تبدیل کنیم؟",
      description:
        "توی این روزا که کلاس های آنلاین همه گیر شده و استفاده از وب کم خیلی بیشترشده یکی از سوال های افراد شاید این باشه که میتونم از گوشی موبایلم به عنوان وب کم استفاده کنم؟\n\nتوی این ویدیو سارا اومده برامون توضیح بده که چجوری میتونیم گوشی موبایلمون رو به وب کم تبدیل کنیم؟\n\nنرم افزارهایی که توی این ویدیو سارا معرفی میکنه برای گوشی های اندروید و آیفون به صورت جداگانه بررسی میشه و طریقه ی استفاده ازش رو هم توضیح میده.\n\nشما از گوشی به عنوان وب کم استفاده میکنید؟\nبرای این کاراز چه نرم افزارهایی استفاده میکنید؟\n\nاگه این",
      username: "mobonews",
      userid: "802491",
      tags: null,
      process: "no_stat",
      sender_name: "موبونیوز",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/41785262-2780-b__444905649.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/41785262-2780__4465.jpg",
      profilePhoto:
        "https://static.cdn.asset.aparat.com//profile-photo/802491-m.jpg",
      duration: "203",
      sdate: "03 بهمن 1400",
      sdate_timediff: 27981,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/kgMfR/vt/frame",
      official: "yes",
      autoplay: true,
      "360d": false,
      brand_priority: "88888",
      like_cnt: "104",
      comment_cnt: 30,
      preview_src: "https://static.cdn.asset.aparat.com/avt/41785262_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "10",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "32168454",
    attributes: {
      id: "32168454",
      title: "جلسه صفرم نکته و تست ریاضی کنکور ۱۴۰۰ مهندس مجتبی لشینی",
      description:
        "لینک زیر را پنجشنبه در مرور گر وارد کنید.\nwww.m-lashini.ir/1400",
      username: "Mojtabalashini",
      userid: "4999703",
      tags: null,
      process: "done",
      sender_name: "Mojtabalashini",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/32168454-6007-b__399415983.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/32168454-6007__1568.jpg",
      profilePhoto:
        "https://www.aparat.com/public/public/user_data/profile_photo/1667/4999703-m.jpg",
      duration: "104",
      sdate: "24 فروردین 1400",
      sdate_timediff: 24634107,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/rLNWf/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: null,
      like_cnt: "24",
      comment_cnt: 43,
      preview_src: "https://static.cdn.asset.aparat.com/avt/32168454_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "3",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "32186244",
    attributes: {
      id: "32186244",
      title:
        "تیزر فیلم تئاتر نا - ب - غه ، ( لینک تماشای فیلم تئاتر در قسمت توضیحات )",
      description:
        "لینک تماشای فیلم تئاتر در سایت تیوال :\r\nhttps://www.tiwall.com/p/nabegheh\r\nنا - ب - غه \r\nنویسنده و کارگردان : مرتضی طالب / بازیگران : محسن ابوالحسنی ، گلنوش قهرمانی / مدیر تصویربرداری : امید غیایی / صدابرداری ، طراحی و ترکیب صدا : شاهین ثابت / تدوین : آریا پور حسینی / عکاس : ارمغان خانمحمدی / تصویربردار : محمد سجادپور \r\nآدرس اینستاگرام :\r\nhttps://www.instagram.com/morteza.taleb7",
      username: "RaHe_ShiRi",
      userid: "10087671",
      tags: null,
      process: "done",
      sender_name: "پادکست تصویری راه شیری",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/32186244-8175-b__501176280.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/32186244-8175__7301.jpg",
      profilePhoto:
        "https://www.aparat.com/public/public/user_data/profile_photo/3363/10087671-m.jpg",
      duration: "53",
      sdate: "25 فروردین 1400",
      sdate_timediff: 24581504,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/2EwMB/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: null,
      like_cnt: "158",
      comment_cnt: 3,
      preview_src: "https://static.cdn.asset.aparat.com/avt/32186244_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "5",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "32193876",
    attributes: {
      id: "32193876",
      title:
        "نشست آزادی تجارت، راهبرد خروج از تنگنای اقتصادی ایران  | تحول 1400",
      description: "",
      username: "AbbasAkhoundi",
      userid: "5811113",
      tags: null,
      process: "done",
      sender_name: "عباس آخوندی",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/32193876-5212-b__204483394.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/32193876-5212__4685.jpg",
      profilePhoto:
        "https://www.aparat.com/public/public/user_data/profile_photo/1938/5811113-m.jpg",
      duration: "3389",
      sdate: "25 فروردین 1400",
      sdate_timediff: 24571626,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/pEQts/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: null,
      like_cnt: "81",
      comment_cnt: 11,
      preview_src: "https://static.cdn.asset.aparat.com/avt/32193876_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "9",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "32199085",
    attributes: {
      id: "32199085",
      title: "دستگاه تراش و تابگیری دیسک چرخ",
      description:
        "دستگاه دیسک تراش درجا یا روکار یونارآک قابلیت تراش و تابگیری و لبه برداری دیسک کلیه خودروهای سواری و شاسی بلنده ایرانی و خارجی را دارا می باشد و دارای قابلیت بالانس توپی با دیسک ترمز است.\r\nاین دستگاه به صورت دستی،اتومات و نیمه اتومات کار می کند و از دو قسمت پاور و کلگی تشکیل شده است.\r\nدارای یک سال گارانتی واقعی و ده سال خدمات پس از فروش می باشد .\r\nشرکت یونارآک علاوه بر دیسک تراش روکار ، کاسه تراش و فلایویل تراش رومیزی نیز برای اولین بار در ایران به تولید رسانده است.\r\nساخت تبریز\r\nجهت کسب اطلاعات بیشتر و ثبت ",
      username: "yonarak",
      userid: "1921216",
      tags: null,
      process: "done",
      sender_name: "yonarak",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/32199085-3971-b__135130558.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/32199085-3971__8940.jpg",
      profilePhoto:
        "https://www.aparat.com/public/public/aparat/img/global/avatar-is-channel.png",
      duration: "54",
      sdate: "25 فروردین 1400",
      sdate_timediff: 24563393,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/6ujLf/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: null,
      like_cnt: "26",
      comment_cnt: 14,
      preview_src: "https://static.cdn.asset.aparat.com/avt/32199085_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "10",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "32196266",
    attributes: {
      id: "32196266",
      title:
        "مفاهیم معامله در بازار های دوطرفه در ایران به زبان خیلی خیلی ساده",
      description:
        "در این ویدیو سلمان یزدانی در صحبت با نازنین موسوی در برنامه سرمایه گذار شو بورسان به زبان خیلی خیلی ساده توضیح می دهد بازار مشتقه چیست. پانزده ویدیوی رایگان برای ورود به بازار مشتقه  در لینک زیر\r\n https://salmanyazdani.com/option/\r\nهمچنین در خبرنامه سایت ثبت نام کنید تا از تخفیفق های ویژه دوره ها مطلع شوید.\r\nwww.salmanyazdani.com",
      username: "salmanyazdani",
      userid: "3989494",
      tags: null,
      process: "done",
      sender_name: "سلمان",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/32196266-7497-b__269404028.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/32196266-7497__1082.jpg",
      profilePhoto:
        "https://www.aparat.com/public/public/user_data/profile_photo/1330/3989494-m.jpg",
      duration: "1012",
      sdate: "25 فروردین 1400",
      sdate_timediff: 24567980,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/Ig3ha/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: null,
      like_cnt: "16",
      comment_cnt: 45,
      preview_src: "https://static.cdn.asset.aparat.com/avt/32196266_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "3",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "32200093",
    attributes: {
      id: "32200093",
      title: "وقتی از شیر کاله حرف می زنیم از چه حرف می زنیم.",
      description:
        "برای تولید «شیر کاله» چه فرآیندی طی می‌شه؟\r\n تماشای این ویدیو ما رو با مرحله به مرحله‌ی تولید این فرآیند آشنا می‌کنه و به تمام سوال‌هامون از ابتدا تا انتهای مسیر تولید پاسخ می‌ده.",
      username: "KallehDairy",
      userid: "603899",
      tags: null,
      process: "done",
      sender_name: "لذت زندگی به روایت کاله",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/32200093-9299-b__299583289.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/32200093-9299__4003.jpg",
      profilePhoto:
        "https://www.aparat.com/public/public/user_data/profile_photo/202/603899-m.jpg",
      duration: "361",
      sdate: "25 فروردین 1400",
      sdate_timediff: 24561768,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/WMOch/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: null,
      like_cnt: "256",
      comment_cnt: 49,
      preview_src: "https://static.cdn.asset.aparat.com/avt/32200093_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "21",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "32198107",
    attributes: {
      id: "32198107",
      title: "نصر الله رادش در برنامه نوروزی و کتاب معجزه سپاس گزاری",
      description:
        "پرفروش ترین کتاب فروردین به چاپ بیستم رسید\nکتاب معجزه سپاس گزاری نوشته راندا برن با ترجمه سیما فرجی در کمتر از یک ماه به چاپ بیستم رسید. \n\nدر برنامه نوروزی شبکه دو نصرالله رادش بازیگر محبوب تلویزیون، از افسردگی خود و نحوه عبور از آن گفتند. ایشان اشاره کردند که کتاب معجزه سپاس گزاری یا معجزه شکر گزاری عامل اصلی برای عبور از این افسردگی بود. تمرین های این کتاب به وی کمک کرد تا بتوانند نگاهی دیگر به دنیا و زندگی بیندازند و از مسیر افسردگی خارج شوند.\n\nتهیه کتاب از وبسایت یا دایرکت اینستاگرام نسل نواندیش یا کتاب",
      username: "NasleNowAndish",
      userid: "1872016",
      tags: null,
      process: "done",
      sender_name: "انتشارات نسل نواندیش",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/32198107-8433-b__471069709.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/32198107-8433__4437.jpg",
      profilePhoto:
        "https://www.aparat.com/public/public/user_data/profile_photo/625/1872016-m.jpg",
      duration: "111",
      sdate: "25 فروردین 1400",
      sdate_timediff: 24564957,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/UM09L/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: null,
      like_cnt: "50",
      comment_cnt: 31,
      preview_src: "https://static.cdn.asset.aparat.com/avt/32198107_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "15",
      tag_rel_id: null,
    },
  },
  {
    type: "Video",
    id: "32164728",
    attributes: {
      id: "32164728",
      title: "میانبر یا شورت کات های متاتریدر",
      description:
        "در این ویدئو آموزشی،با میانبر یا شورت کات های متاتریدر آشنا شوید.",
      username: "AMarkets_Persian",
      userid: "5963615",
      tags: null,
      process: "done",
      sender_name: "AMarkets_Persian",
      big_poster:
        "https://static.cdn.asset.aparat.com/avt/32164728-4871-b__447691649.jpg",
      small_poster:
        "https://static.cdn.asset.aparat.com/avt/32164728-4871__1707.jpg",
      profilePhoto:
        "https://www.aparat.com/public/public/user_data/profile_photo/1988/5963615-m.jpg",
      duration: "259",
      sdate: "24 فروردین 1400",
      sdate_timediff: 24641869,
      frame:
        "https://www.aparat.com/video/video/embed/videohash/wGY1q/vt/frame",
      official: "no",
      autoplay: true,
      "360d": false,
      brand_priority: null,
      like_cnt: "32",
      comment_cnt: 35,
      preview_src: "https://static.cdn.asset.aparat.com/avt/32164728_15s.mp4",
      file_link_all: null,
      file_link: null,
      videovisit: null,
      like: null,
      share: null,
      meta: null,
      catId: "16",
      tag_rel_id: null,
    },
  },
];

export { VIDEOS };
